// GENERATED by highlight/generate.ts — do not edit by hand.
// Regenerate with: bun run gen:era1-highlight
import type { CompletionToken, PrefixToken } from "./index";

export const SOURCE_FINGERPRINT = "0e891d67-6b0";

export const PREFIX_TOKENS: Record<string, PrefixToken[]> = {
  "reverse-fn": [
    {
      "d": "#F97583",
      "k": "keyword",
      "l": "#D73A49",
      "t": "function"
    },
    {
      "d": "#E1E4E8",
      "k": "plain",
      "l": "#24292E",
      "t": " "
    },
    {
      "d": "#B392F0",
      "k": "plain",
      "l": "#6F42C1",
      "t": "reverseList"
    },
    {
      "d": "#E1E4E8",
      "k": "punct",
      "l": "#24292E",
      "t": "("
    },
    {
      "d": "#FFAB70",
      "k": "plain",
      "l": "#E36209",
      "t": "items"
    },
    {
      "d": "#E1E4E8",
      "k": "punct",
      "l": "#24292E",
      "t": ") {"
    },
    {
      "d": "#E1E4E8",
      "k": "plain",
      "l": "#24292E",
      "t": "\n"
    },
    {
      "d": "#E1E4E8",
      "k": "plain",
      "l": "#24292E",
      "t": "  "
    },
    {
      "d": "#F97583",
      "k": "keyword",
      "l": "#D73A49",
      "t": "return"
    },
    {
      "d": "#E1E4E8",
      "k": "plain",
      "l": "#24292E",
      "t": " "
    }
  ],
  "how-do-i": [
    {
      "d": "#6A737D",
      "k": "comment",
      "l": "#6A737D",
      "t": "// how do I reverse a list in JavaScript?"
    },
    {
      "d": "#E1E4E8",
      "k": "plain",
      "l": "#24292E",
      "t": "\n"
    }
  ]
};

export const COMPLETION_TOKENS: Record<string, CompletionToken[]> = {
  "reverse-fn:base:low": [
    {
      "k": "plain",
      "t": "items."
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "();"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "}"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "keyword",
      "t": "function"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "plain",
      "t": "reverseList"
    },
    {
      "k": "punct",
      "t": "("
    },
    {
      "k": "plain",
      "t": "items"
    },
    {
      "k": "punct",
      "t": ") {"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "  "
    },
    {
      "k": "keyword",
      "t": "return"
    },
    {
      "k": "plain",
      "t": " items."
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "();"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "punct",
      "t": "}"
    },
    {
      "k": "plain",
      "t": "\n"
    }
  ],
  "reverse-fn:instruct:low": [
    {
      "k": "plain",
      "t": "items."
    },
    {
      "k": "plain",
      "t": "slice"
    },
    {
      "k": "plain",
      "t": "()."
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "();"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "}"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "comment",
      "t": "// slice() copies first, so the original array is untouched."
    }
  ],
  "reverse-fn:base:mid": [
    {
      "k": "plain",
      "t": "items."
    },
    {
      "k": "plain",
      "t": "slice"
    },
    {
      "k": "plain",
      "t": "()."
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "();"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "}"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "comment",
      "t": "// reverse a string too"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "keyword",
      "t": "function"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "plain",
      "t": "reverseStr"
    },
    {
      "k": "punct",
      "t": "("
    },
    {
      "k": "plain",
      "t": "s"
    },
    {
      "k": "punct",
      "t": ") {"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "  "
    },
    {
      "k": "keyword",
      "t": "return"
    },
    {
      "k": "plain",
      "t": " s."
    },
    {
      "k": "plain",
      "t": "split"
    },
    {
      "k": "plain",
      "t": "("
    },
    {
      "k": "string",
      "t": "''"
    },
    {
      "k": "plain",
      "t": ")"
    }
  ],
  "reverse-fn:instruct:mid": [
    {
      "k": "plain",
      "t": "items."
    },
    {
      "k": "plain",
      "t": "slice"
    },
    {
      "k": "plain",
      "t": "()."
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "();"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "}"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "comment",
      "t": "// slice() copies the array first, so the original is left untouched."
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "comment",
      "t": "// reverse() on its own would mutate it in place."
    }
  ],
  "reverse-fn:base:high": [
    {
      "k": "plain",
      "t": "items."
    },
    {
      "k": "plain",
      "t": "reduceRight"
    },
    {
      "k": "plain",
      "t": "(("
    },
    {
      "k": "plain",
      "t": "a"
    },
    {
      "k": "punct",
      "t": ","
    },
    {
      "k": "plain",
      "t": "b"
    },
    {
      "k": "punct",
      "t": ")"
    },
    {
      "k": "keyword",
      "t": "=>"
    },
    {
      "k": "plain",
      "t": "["
    },
    {
      "k": "keyword",
      "t": "..."
    },
    {
      "k": "plain",
      "t": "a,b],[]);"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "}"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "keyword",
      "t": "const"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "plain",
      "t": "x"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "keyword",
      "t": "="
    },
    {
      "k": "plain",
      "t": " 🦆; "
    },
    {
      "k": "comment",
      "t": "// TODO: ship it"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "keyword",
      "t": "export"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "keyword",
      "t": "default"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "keyword",
      "t": "function"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "plain",
      "t": "App"
    },
    {
      "k": "punct",
      "t": "(){"
    },
    {
      "k": "keyword",
      "t": "return"
    }
  ],
  "reverse-fn:instruct:high": [
    {
      "k": "plain",
      "t": "items."
    },
    {
      "k": "plain",
      "t": "slice"
    },
    {
      "k": "plain",
      "t": "()."
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "();"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "}"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "comment",
      "t": "// slice() copies first — the original survives. reverse() alone"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "comment",
      "t": "// would not. Newer runtimes have toReversed(), which copies for you."
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "comment",
      "t": "// Whether you needed a reversed copy is a separate question entirely."
    }
  ],
  "how-do-i:base:low": [
    {
      "k": "comment",
      "t": "// how do I sort a list in JavaScript?"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "comment",
      "t": "// how do I filter a list in JavaScript?"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "comment",
      "t": "// how do I"
    }
  ],
  "how-do-i:instruct:low": [
    {
      "k": "plain",
      "t": "Use "
    },
    {
      "k": "plain",
      "t": "slice"
    },
    {
      "k": "plain",
      "t": "() to copy the array, then "
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "():"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "keyword",
      "t": "const"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "plain",
      "t": "reversed"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "keyword",
      "t": "="
    },
    {
      "k": "plain",
      "t": " items."
    },
    {
      "k": "plain",
      "t": "slice"
    },
    {
      "k": "plain",
      "t": "()."
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "();"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "Calling "
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "() alone would mutate the original."
    }
  ],
  "how-do-i:base:mid": [
    {
      "k": "comment",
      "t": "// and how do I do it without mutating the original?"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "comment",
      "t": "// is reverse() stable?"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "comment",
      "t": "// why does this matter?"
    },
    {
      "k": "plain",
      "t": "\n"
    }
  ],
  "how-do-i:instruct:mid": [
    {
      "k": "plain",
      "t": "Copy the array first, then reverse "
    },
    {
      "k": "plain",
      "t": "it"
    },
    {
      "k": "punct",
      "t": ":"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "keyword",
      "t": "const"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "plain",
      "t": "reversed"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "keyword",
      "t": "="
    },
    {
      "k": "plain",
      "t": " items."
    },
    {
      "k": "plain",
      "t": "slice"
    },
    {
      "k": "plain",
      "t": "()."
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "();"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "() on its own mutates the array "
    },
    {
      "k": "keyword",
      "t": "in"
    },
    {
      "k": "plain",
      "t": " place, which is"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "rarely what you want."
    }
  ],
  "how-do-i:base:high": [
    {
      "k": "comment",
      "t": "// how do I reverse time? how do I reverse a decision?"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "comment",
      "t": "// what is a list, really? who is asking?"
    },
    {
      "k": "plain",
      "t": "\n"
    }
  ],
  "how-do-i:instruct:high": [
    {
      "k": "plain",
      "t": "Copy it first, then "
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "punct",
      "t": ":"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "keyword",
      "t": "const"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "plain",
      "t": "reversed"
    },
    {
      "k": "plain",
      "t": " "
    },
    {
      "k": "keyword",
      "t": "="
    },
    {
      "k": "plain",
      "t": " items."
    },
    {
      "k": "plain",
      "t": "slice"
    },
    {
      "k": "plain",
      "t": "()."
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "();"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "reverse"
    },
    {
      "k": "plain",
      "t": "() alone mutates "
    },
    {
      "k": "keyword",
      "t": "in"
    },
    {
      "k": "plain",
      "t": " place. If your runtime is recent enough,"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "toReversed"
    },
    {
      "k": "plain",
      "t": "() does the copying for you. And "
    },
    {
      "k": "keyword",
      "t": "if"
    },
    {
      "k": "plain",
      "t": " the list is large"
    },
    {
      "k": "plain",
      "t": "\n"
    },
    {
      "k": "plain",
      "t": "enough to worry about, you probably wanted an iterator instead."
    }
  ]
};
