/**
 * Tokenises the answer the presenter carries from the browser into the editor,
 * and writes it to `tokens.generated.ts`. Run with
 * `bun run gen:era2-highlight` from `apps/web`.
 *
 * Imports Shiki and is never bundled — nothing in the client tree imports it.
 *
 * The fingerprint below only catches THREAD_ANSWER changing. It cannot catch a
 * `shiki` version bump changing grammars or themes underneath the committed
 * tokens — no test can detect that drift, so re-run this by hand after any
 * `shiki` upgrade.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { createHighlighter } from "shiki";
import { fingerprintText, kindFromScopes } from "../../highlight";
import {
  applySuggestion,
  INITIAL_FILE,
  resolveMismatch,
  SUGGESTION,
} from "../apply";
import { THREAD_ANSWER } from "../extraction";
import type { EditorToken, FilePhase } from "./index";

const THEME = "github-dark";

const highlighter = await createHighlighter({
  langs: ["javascript"],
  themes: [THEME],
});

const source = THREAD_ANSWER.join("\n");

function tokeniseToLines(code: string): EditorToken[][] {
  return highlighter
    .codeToTokens(code, {
      includeExplanation: "scopeName",
      lang: "javascript",
      theme: THEME,
    })
    .tokens.map((line) =>
      line.map((t) => ({
        c: t.color ?? "#D4D4D4",
        k: kindFromScopes(
          t.explanation?.[0]?.scopes.map((s) => s.scopeName) ?? []
        ),
        t: t.content,
      }))
    );
}

// The demo's own pure functions produce these, so the committed tokens
// describe exactly what the component will render.
const appliedFile = applySuggestion(INITIAL_FILE, SUGGESTION).file;
const resolvedFile = resolveMismatch(appliedFile, SUGGESTION);

/** Explicit order — the fingerprint depends on it. */
const FILE_SOURCES: readonly [FilePhase, string][] = [
  ["initial", INITIAL_FILE.lines.join("\n")],
  ["applied", appliedFile.lines.join("\n")],
  ["resolved", resolvedFile.lines.join("\n")],
];

const fileTokens: Record<string, EditorToken[][]> = {};
for (const [phase, code] of FILE_SOURCES) {
  fileTokens[phase] = tokeniseToLines(code);
}

const lines: EditorToken[][] = tokeniseToLines(source);

const body = `// GENERATED by highlight/generate.ts — do not edit by hand.
// Regenerate with: bun run gen:era2-highlight
import type { EditorToken, FilePhase } from "./index";

export const SOURCE_FINGERPRINT = ${JSON.stringify(fingerprintText([...THREAD_ANSWER]))};

export const EDITOR_TOKENS: EditorToken[][] = ${JSON.stringify(lines, null, 2)};

export const FILE_FINGERPRINT = ${JSON.stringify(fingerprintText(FILE_SOURCES.map(([, code]) => code)))};

export const FILE_TOKENS: Record<FilePhase, EditorToken[][]> = ${JSON.stringify(fileTokens, null, 2)};
`;

writeFileSync(join(import.meta.dir, "tokens.generated.ts"), body);
process.stdout.write(
  `wrote ${lines.length} answer lines and ${FILE_SOURCES.length} file states\n`
);
