// GENERATED by highlight/generate.ts — do not edit by hand.
// Regenerate with: bun run gen:era2-highlight
import type { EditorToken, FilePhase } from "./index";

export const SOURCE_FINGERPRINT = "14762d82-84";

export const EDITOR_TOKENS: EditorToken[][] = [
  [
    {
      "c": "#F97583",
      "k": "keyword",
      "t": "function"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": " "
    },
    {
      "c": "#B392F0",
      "k": "plain",
      "t": "validateCode"
    },
    {
      "c": "#E1E4E8",
      "k": "punct",
      "t": "("
    },
    {
      "c": "#FFAB70",
      "k": "plain",
      "t": "code"
    },
    {
      "c": "#E1E4E8",
      "k": "punct",
      "t": ") {"
    }
  ],
  [
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": "  "
    },
    {
      "c": "#F97583",
      "k": "keyword",
      "t": "if"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": " ("
    },
    {
      "c": "#F97583",
      "k": "keyword",
      "t": "!"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": "(code "
    },
    {
      "c": "#F97583",
      "k": "keyword",
      "t": "in"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": " "
    },
    {
      "c": "#79B8FF",
      "k": "plain",
      "t": "DISCOUNTS"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": ")) {"
    }
  ],
  [
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": "    "
    },
    {
      "c": "#F97583",
      "k": "keyword",
      "t": "return"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": " { ok: "
    },
    {
      "c": "#79B8FF",
      "k": "plain",
      "t": "false"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": " };"
    }
  ],
  [
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": "  }"
    }
  ],
  [
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": "  "
    },
    {
      "c": "#F97583",
      "k": "keyword",
      "t": "return"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": " { ok: "
    },
    {
      "c": "#79B8FF",
      "k": "plain",
      "t": "true"
    },
    {
      "c": "#E1E4E8",
      "k": "punct",
      "t": ", rate: "
    },
    {
      "c": "#79B8FF",
      "k": "plain",
      "t": "DISCOUNTS"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": "[code] };"
    }
  ],
  [
    {
      "c": "#E1E4E8",
      "k": "punct",
      "t": "}"
    }
  ]
];

export const FILE_FINGERPRINT = "f73691ef-25b";

export const FILE_TOKENS: Record<FilePhase, EditorToken[][]> = {
  "initial": [
    [
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "function"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#B392F0",
        "k": "plain",
        "t": "applyDiscount"
      },
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": "("
      },
      {
        "c": "#FFAB70",
        "k": "plain",
        "t": "cart"
      },
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": ", "
      },
      {
        "c": "#FFAB70",
        "k": "plain",
        "t": "code"
      },
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": ") {"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "  "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "const"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#79B8FF",
        "k": "plain",
        "t": "rate"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "="
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#79B8FF",
        "k": "plain",
        "t": "DISCOUNTS"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "[code];"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "  "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "return"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " cart.total "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "*"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " ("
      },
      {
        "c": "#79B8FF",
        "k": "plain",
        "t": "1"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "-"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " rate);"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": "}"
      }
    ]
  ],
  "applied": [
    [
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "function"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#B392F0",
        "k": "plain",
        "t": "applyDiscount"
      },
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": "("
      },
      {
        "c": "#FFAB70",
        "k": "plain",
        "t": "cart"
      },
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": ", "
      },
      {
        "c": "#FFAB70",
        "k": "plain",
        "t": "code"
      },
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": ") {"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "  "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "const"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#79B8FF",
        "k": "plain",
        "t": "rate"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "="
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#79B8FF",
        "k": "plain",
        "t": "DISCOUNTS"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "[code];"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "  "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "if"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " ("
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "!"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "(code "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "in"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#79B8FF",
        "k": "plain",
        "t": "DISCOUNTS"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": ")) {"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "    "
      },
      {
        "c": "#B392F0",
        "k": "plain",
        "t": "logEvent"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "("
      },
      {
        "c": "#9ECBFF",
        "k": "string",
        "t": "\"bad_discount_code\""
      },
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": ", { code });"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "    "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "throw"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "new"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#B392F0",
        "k": "plain",
        "t": "Error"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "("
      },
      {
        "c": "#9ECBFF",
        "k": "string",
        "t": "\"Unknown discount code\""
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": ");"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "  }"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "  "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "return"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " cart.total "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "*"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " ("
      },
      {
        "c": "#79B8FF",
        "k": "plain",
        "t": "1"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "-"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " rate);"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": "}"
      }
    ]
  ],
  "resolved": [
    [
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "import"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " { logEvent } "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "from"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#9ECBFF",
        "k": "string",
        "t": "\"./analytics\""
      },
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": ";"
      }
    ],
    [],
    [
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "function"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#B392F0",
        "k": "plain",
        "t": "applyDiscount"
      },
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": "("
      },
      {
        "c": "#FFAB70",
        "k": "plain",
        "t": "cart"
      },
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": ", "
      },
      {
        "c": "#FFAB70",
        "k": "plain",
        "t": "code"
      },
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": ") {"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "  "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "const"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#79B8FF",
        "k": "plain",
        "t": "rate"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "="
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#79B8FF",
        "k": "plain",
        "t": "DISCOUNTS"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "[code];"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "  "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "if"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " ("
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "!"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "(code "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "in"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#79B8FF",
        "k": "plain",
        "t": "DISCOUNTS"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": ")) {"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "    "
      },
      {
        "c": "#B392F0",
        "k": "plain",
        "t": "logEvent"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "("
      },
      {
        "c": "#9ECBFF",
        "k": "string",
        "t": "\"bad_discount_code\""
      },
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": ", { code });"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "    "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "throw"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "new"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#B392F0",
        "k": "plain",
        "t": "Error"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "("
      },
      {
        "c": "#9ECBFF",
        "k": "string",
        "t": "\"Unknown discount code\""
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": ");"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "  }"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": "  "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "return"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " cart.total "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "*"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " ("
      },
      {
        "c": "#79B8FF",
        "k": "plain",
        "t": "1"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " "
      },
      {
        "c": "#F97583",
        "k": "keyword",
        "t": "-"
      },
      {
        "c": "#E1E4E8",
        "k": "plain",
        "t": " rate);"
      }
    ],
    [
      {
        "c": "#E1E4E8",
        "k": "punct",
        "t": "}"
      }
    ]
  ]
};
