// GENERATED by highlight/generate.ts — do not edit by hand.
// Regenerate with: bun run gen:era2-highlight
import type { EditorToken } from "./index";

export const SOURCE_FINGERPRINT = "14762d82-84";

export const EDITOR_TOKENS: EditorToken[][] = [
  [
    {
      "c": "#F97583",
      "k": "keyword",
      "t": "function"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": " "
    },
    {
      "c": "#B392F0",
      "k": "plain",
      "t": "validateCode"
    },
    {
      "c": "#E1E4E8",
      "k": "punct",
      "t": "("
    },
    {
      "c": "#FFAB70",
      "k": "plain",
      "t": "code"
    },
    {
      "c": "#E1E4E8",
      "k": "punct",
      "t": ") {"
    }
  ],
  [
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": "  "
    },
    {
      "c": "#F97583",
      "k": "keyword",
      "t": "if"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": " ("
    },
    {
      "c": "#F97583",
      "k": "keyword",
      "t": "!"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": "(code "
    },
    {
      "c": "#F97583",
      "k": "keyword",
      "t": "in"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": " "
    },
    {
      "c": "#79B8FF",
      "k": "plain",
      "t": "DISCOUNTS"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": ")) {"
    }
  ],
  [
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": "    "
    },
    {
      "c": "#F97583",
      "k": "keyword",
      "t": "return"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": " { ok: "
    },
    {
      "c": "#79B8FF",
      "k": "plain",
      "t": "false"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": " };"
    }
  ],
  [
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": "  }"
    }
  ],
  [
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": "  "
    },
    {
      "c": "#F97583",
      "k": "keyword",
      "t": "return"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": " { ok: "
    },
    {
      "c": "#79B8FF",
      "k": "plain",
      "t": "true"
    },
    {
      "c": "#E1E4E8",
      "k": "punct",
      "t": ", rate: "
    },
    {
      "c": "#79B8FF",
      "k": "plain",
      "t": "DISCOUNTS"
    },
    {
      "c": "#E1E4E8",
      "k": "plain",
      "t": "[code] };"
    }
  ],
  [
    {
      "c": "#E1E4E8",
      "k": "punct",
      "t": "}"
    }
  ]
];
